import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'swiper/css';
import { Toaster } from "react-hot-toast";
import { HeroUIProvider } from "@heroui/react";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "SUMA Barbershop",
  description: "Generated by create next app",
  // 👇 ini bagian penting agar manifest dikenali
  manifest: "/manifest.json",
  themeColor: "#0f172a",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* 👇 manual fallback jika metadata belum terdeteksi */}
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        <meta name="theme-color" content="#0f172a" />
      </head>
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <HeroUIProvider>
          <Toaster position="top-center" />
          {children}
        </HeroUIProvider>
      </body>
    </html>
  );
}
